<a href="https://colab.research.google.com/github/Gongster123/class2022spring/blob/main/0316.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 1
b = 2
c = 3

In [ ]:
print(a)

1


In [ ]:
print(type(a))

<class 'int'>


In [ ]:
d = a + b + c
print(d)

6


In [ ]:
a='hello'

In [ ]:
print(a)

hello


In [ ]:
print(type(a))
print(a[2])

<class 'str'>
l


In [ ]:
a = [1, 2, 3, "abc", [7, 8, 'z']]

In [ ]:
print(a)

[1, 2, 3, 'abc', [7, 8, 'z']]


In [ ]:
print(type(a))
print(a[2])
print((a[4][0]))

<class 'list'>
3
7


In [ ]:
a = {'a':'apple', 'b':'orange', 'c':1999}
print(type(a))
print(a)
print(a['b'])

<class 'dict'>
{'a': 'apple', 'b': 'orange', 'c': 1999}
orange


In [ ]:
x = 'abcdefu'
print(x[0])

a


In [ ]:
print(x[2:5])
print(x[:3])
print(x[2:])

cde
abc
cdefu


In [ ]:


len(x)
x.upper()

'ABCDEFU'

In [ ]:
s= 'this is a huse i built this year'
s

'this is a huse i built this year'

In [ ]:
s.strip()

'this is a huse i built this year'

In [ ]:
tokens=s.split(' ')
print(tokens)

['this', 'is', 'a', 'huse', 'i', 'built', 'this', 'year']


In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
print(x)
print(type(x))
print(x.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [ ]:
x = np.arange(0,10,2)
print(x)
print(type(x))
print(x.shape)

[0 2 4 6 8]
<class 'numpy.ndarray'>
(5,)


In [ ]:
x = np.linspace(0,10,6)
print(x)
print(type(x))
print(x.shape)

[ 0.  2.  4.  6.  8. 10.]
<class 'numpy.ndarray'>
(6,)


In [ ]:
x = np.array([[1,2,3], [4,5,6]])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(x)
print(type(x))
print(x.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
x = np.ones([2, 2, 3])
print(x)
print(type(x))
print(x.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
x = np.zeros([2, 2, 3])
print(x)
print(type(x))
print(x.shape)
x.reshape(3,2,2)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>
(2, 2, 3)


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])